### ISSUE TITLE
Implementing the Minnesota Code

### ISSUE THREAD

**Issue by AbhishekEkhare** [snorbi07/MinnesotaCode#4]
Sir,
I have been studying your work on Minnesota Code implementation.
Your codes considers only the first Minnesota rule.
I am trying to further extend your code to the other rules.

However, i am unable to understand the dataset(ECG values) that you have used as input.
Can you please tell me how you calculated the parameters in the dataset ??

Furthermore, i am unable to understand some of the values that you have used, like QRS_INT_MEAN, QRS_AXIS, QRS_AXIS_3D, V1_P1_INT, V1_P2_INT, V1_P1_AMP, V1_P2_AMP, V1_P1_AREA, V1_P2_AREA, QRS_PTP_I, QRS_BIAS_I and ST_DEV_I ??

Awaiting your guidance.

Thanks and regards,
Abhishek.

**Comment by snorbi07** [comment]
Dear @AbhishekEkhare ,

Most of those values I got from a colleague, who was focusing on ECG signal processing. I'll have to look up my notes and check the details.  I'll do that and get back to you sometimes next week.

Regards,
Norbert

**Comment by AbhishekEkhare** [comment]
Hello Sir,
Eagerly awaiting your reply and guidance.

Regards,
Abhishek.

**Comment by snorbi07** [comment]
Hello, @AbhishekEkhare 

The used dataset is the output of various [PhysioNet](http://www.physionet.org/) databases. For example one of the used databases was the [Incart DB](http://www.physionet.org/pn3/incartdb/). 
I did not work on processing the datasets, it was done by one of my colleagues. Note, not all extracted values are targeted for the Minnesota code processing. You could try to use the annotators provided by PhysioNet as well. 

As for the values, they follow a certain naming convention. For example:
- QRS_INT_MEAN stands for QRS complex interval average.
- ST_DEV_I stands for ST segment deviation in case of ECG lead I.

Used descriptors: 
INT = interval
PTP = peak to peak (ECG peak)
AMP = amplitude
DEV = deviation

If I recall correctly, P1 means peak number 1 in a single [ECG signal](https://en.wikipedia.org/wiki/Electrocardiography).

When you see a value name ending in I, II, V1, V6, ... those are used to identify the specific ECG lead.

Hope this helps!

Regards,
Norbi

**Comment by AbhishekEkhare** [comment]
Hello Sir,
Thank you very much for such a detailed explanation.

1) I have managed to calculate ECG_QRS_AXIS as arctan(ECG_R_AMP_AVF / ECG_R_AMP_I) \* (180 / pi).
Can you please tell me what ECG_QRS_AXIS_3D is??

2) ECG_QRS_INT_MEAN is calculated from which ECG Lead ??

3) Also, does P1 means the number-1 R-peak  and P2 means number-2 R-peak in a single ECG signal ??

Thank you in advance.

Regards,
Abhishek.

**Comment by snorbi07** [comment]
> Can you please tell me what ECG_QRS_AXIS_3D is??

That is a custom entry. The 3rd dimension pointing outwards from the patient's hearth. The standard measures in the head/leg axis, this one in the 3rd dimension.

> ECG_QRS_INT_MEAN is calculated from which ECG Lead ??

This is "global". The beginning and the end of the QRS is aligned for all channels. If we would calculate it separately for each channel, there would be minor differences, however automated algorithms were more stable this way.

>  Also, does P1 means the number-1 R-peak and P2 means number-2 R-peak in a single ECG signal ??

In case the T wave or the P wave is "biphased", then the ECG signal has two peaks. The first being P1, the second P2. Regardless whether it is positive or negative.

**Comment by AbhishekEkhare** [comment]
Sir,
Thank you very much for replying.

//"That is a custom entry. The 3rd dimension pointing outwards from the patient's hearth. The standard measures in the head/leg axis, this one in the 3rd dimension."//
Can you please mention the formula/equation used to calculate the QRS Axis in 3rd dimension.

"In case the T wave or the P wave is "biphased", then the ECG signal has two peaks. The first being P1, the second P2. Regardless whether it is positive or negative."
Since we are using the naming convention 'ECG_V1_P1_INT" etc, does that mean we are looking for biphased P-waves/T-waves in Lead-V1 only ??

Also, how have you calculated Q_INT, R_INT and S_INT ?? Are they the individual Q,R,S components of a single QRS wave ?? I am asking this question because the Q_INT + R_INT + S_INT do not add up to QRS_INT.

Thank you in advance.

Regards,
Abhishek.

**Comment by AbhishekEkhare** [comment]
Sir,
If possible, i request you to please address my queries as that would help me complete my dataset.

Thanks and regards,
Abhishek.

**Comment by snorbi07** [comment]
Hi @AbhishekEkhare,
I apologize for not responding earlier, I've been busy.

> Can you please mention the formula/equation used to calculate the QRS Axis in 3rd dimension.

Sorry, I don't know. As I mentioned I've acquired this dataset from one of my colleagues. If I remember correctly, they used this for some experiments only.

> Since we are using the naming convention 'ECG_V1_P1_INT" etc, does that mean we are looking for biphased P-waves/T-waves in Lead-V1 only ??

To my knowledge, yes.

> Also, how have you calculated Q_INT, R_INT and S_INT ?? Are they the individual Q,R,S components of a single QRS wave ?? I am asking this question because the Q_INT + R_INT + S_INT do not add up to QRS_INT.

I'm not sure. I'll try to find it out and get back to you if I have an answer.

**Comment by AbhishekEkhare** [comment]
Hi Sir,
Thank you very much for replying.
I will wait for your reply as i would not be able to move ahead without completing my dataset.

Regards,
Abhishek.

**Comment by snorbi07** [comment]
Unfortunately, I couldn't reach my colleague to inquire about the calculation details. 
For the QRS_INT calculation, minor differences might be the cause of rounding or slightly different algorithms. However you could try running a Physionet annotator on the signals and compare the results.

**Comment by snorbi07** [comment]
Update:
The Q_INT starts from the beginning of the QRS wave until the end of the Q wave. However this was detected by a different algorithm. This can be the cause of some differences.

Hope this helps you!

**Comment by snorbi07** [comment]
I'll close the ticket for now. If you have further questions, just contact me.
